spring.application.name=product-search-api
server.port=8992

spring.datasource.url=jdbc:mysql://localhost:3306/product_db
spring.datasource.username=root
spring.datasource.password=Revanth@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
